### ISSUE TITLE
Run Exception 

### ISSUE THREAD

**Issue by khiemnd5** [jianqi/play-store-crawler#1]
### I ran project for you but It have got exception:

> Send Http POST request
> 
> Sending 'POST' request to URL : https://play.google.com/store/getreviews
> Post parameters : reviewType=0&pageNum=0&id=com.gameloft.android.ANMP.GloftDMHM&reviewSortOrder=2&xhr=1
> Response Code : 200
> java.lang.NumberFormatException: For input string: ""

Can you support me.?
You can reply here or send my email :khiemnd5@gmail.com
Thank you so much!.

**Comment by khiemnd5** [comment]
Ok, Thank you so much because you replied me.
I ran project of you very good.
But, I have a problem new. This is : When i run 3 times project =>
exception new
 503 .
https://ipv4.google.com/sorry/IndexRedirect?continue=https://play.google.com/store/getreviews&q=CGMSBHUAN3MY0KvFrQUiGQDxp4NL8xTkhFfn83fkESgxW0V0nrDjXGY

So, i can't get more reviews. I think problem here this is google suppose
robot so They deny access.

2015-07-24 23:10 GMT+07:00 jianqi notifications@github.com:

**Comment by jianqi** [comment]
yea. by right they don't allow people to crawl their review data.

**Comment by amitthorat13** [comment]
Hey i am trying to run these example but i am getting the following error ....Please can you fix it buy helping me ??

Email-id:-amit94thorat@gmail.com




Send Http POST request

Sending 'POST' request to URL : https://play.google.com/store/getreviews
Post parameters : reviewType=0&pageNum=0&id=com.imgur.mobile&reviewSortOrder=2&xhr=1
Response Code : 200
